services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ideasoft_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./logs:/var/log/php
    networks:
      - laravel_network
    environment:
      - APP_ENV=local

  webserver:
    image: nginx:latest
    container_name: ideasoft_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: ideasoft_mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_turkish_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
